import { ProjectType, type ProjectsList } from '@interfaces/types.d';

const { MOBILE, WEB } = ProjectType;

export const PROJECTS_LIST: ProjectsList = {
  '1': {
    id: '1',
    title: 'Botica Junin',
    type: MOBILE,
    images: [
      '../../images/projects/boticaJunin/botica-junin-image-1.png',
      '../../images/projects/boticaJunin/botica-junin-image-2.png',
      '../../images/projects/boticaJunin/botica-junin-image-3.png',
      '../../images/projects/boticaJunin/botica-junin-image-4.png',
      '../../images/projects/boticaJunin/botica-junin-image-5.png',
      '../../images/projects/boticaJunin/botica-junin-image-6.png',
    ],
    technologies: ['Ionic', 'Angular', 'TypeScript', 'Git'],
  },
  '2': {
    id: '2',
    title: 'Wayu Inc',
    type: WEB,
    images: [
      '../../images/projects/wayuInc/wayu-inc-image-1.png',
      '../../images/projects/wayuInc/wayu-inc-image-2.png',
      '../../images/projects/wayuInc/wayu-inc-image-3.png',
      '../../images/projects/wayuInc/wayu-inc-image-4.png',
      '../../images/projects/wayuInc/wayu-inc-image-5.png',
      '../../images/projects/wayuInc/wayu-inc-image-6.png',
    ],
    technologies: ['Angular', 'TypeScript', 'Html', 'Sass', 'Git'],
  },
  '3': {
    id: '3',
    title: 'Slon Care',
    type: WEB,
    images: [
      '../../images/projects/slonCare/slon-care-image-1.png',
      '../../images/projects/slonCare/slon-care-image-2.png',
      '../../images/projects/slonCare/slon-care-image-3.png',
      '../../images/projects/slonCare/slon-care-image-4.png',
      '../../images/projects/slonCare/slon-care-image-5.png',
      '../../images/projects/slonCare/slon-care-image-6.png',
    ],
    technologies: ['Angular', 'TypeScript', 'Html', 'Sass', 'Git'],
  },
  '4': {
    id: '4',
    title: 'Bison Reserve Landing Page',
    type: WEB,
    images: [
      '../../images/projects/bisonReserveWeb/bison-reserve-web-image-1.png',
      '../../images/projects/bisonReserveWeb/bison-reserve-web-image-2.png',
      '../../images/projects/bisonReserveWeb/bison-reserve-web-image-3.png',
      '../../images/projects/bisonReserveWeb/bison-reserve-web-image-4.png',
      '../../images/projects/bisonReserveWeb/bison-reserve-web-image-5.png',
      '../../images/projects/bisonReserveWeb/bison-reserve-web-image-6.png',
    ],
    technologies: ['React', 'JavaScript', 'Html', 'Css', 'Git'],
  },
  '5': {
    id: '5',
    title: 'Bison Reserve App',
    type: MOBILE,
    images: [
      '../../images/projects/bisonReserveApp/bison-reserve-app-image-1.png',
      '../../images/projects/bisonReserveApp/bison-reserve-app-image-2.png',
      '../../images/projects/bisonReserveApp/bison-reserve-app-image-3.png',
      '../../images/projects/bisonReserveApp/bison-reserve-app-image-4.png',
      '../../images/projects/bisonReserveApp/bison-reserve-app-image-5.png',
      '../../images/projects/bisonReserveApp/bison-reserve-app-image-6.png',
    ],
    technologies: ['React Native', 'JavaScript', 'Redux', 'Git'],
  },
  '6': {
    id: '6',
    title: 'Marbyl App',
    type: MOBILE,
    images: [
      '../../images/projects/marbyl/marbyl-image-1.png',
      '../../images/projects/marbyl/marbyl-image-2.png',
      '../../images/projects/marbyl/marbyl-image-3.png',
      '../../images/projects/marbyl/marbyl-image-4.png',
      '../../images/projects/marbyl/marbyl-image-5.png',
      '../../images/projects/marbyl/marbyl-image-6.png',
    ],
    technologies: ['React Native', 'JavaScript', 'GraphQL', 'AWS Services', 'Redux', 'Git'],
  },
  '7': {
    id: '7',
    title: 'Pavimenti Store App',
    type: MOBILE,
    images: [
      '../../images/projects/pavimenti/pavimenti-app-image-1.png',
      '../../images/projects/pavimenti/pavimenti-app-image-2.png',
      '../../images/projects/pavimenti/pavimenti-app-image-3.png',
      '../../images/projects/pavimenti/pavimenti-app-image-4.png',
      '../../images/projects/pavimenti/pavimenti-app-image-5.png',
      '../../images/projects/pavimenti/pavimenti-app-image-6.png',
    ],
    technologies: ['React Native', 'JavaScript', 'Redux', 'Git'],
  },
  '8': {
    id: '8',
    title: 'Alternos',
    type: WEB,
    images: [
      '../../images/projects/alternos/alternos-image-1.png',
      '../../images/projects/alternos/alternos-image-2.png',
      '../../images/projects/alternos/alternos-image-3.png',
      '../../images/projects/alternos/alternos-image-4.png',
      '../../images/projects/alternos/alternos-image-5.png',
      '../../images/projects/alternos/alternos-image-6.png',
    ],
    technologies: ['React', 'JavaScript', 'Html', 'Css', 'Git'],
  },
};
